
const INDEX_URL = "data/index.json"; const PAGE_SIZE = 24;
const qs = (s, el=document) => el.querySelector(s); const qsa = (s, el=document) => Array.from(el.querySelectorAll(s));
async function safeJson(url){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(r.status);return await r.json()}catch(e){console.warn('Failed',url,e);return null}}
async function loadIndex(){return safeJson(INDEX_URL)} async function loadCategory(u){return safeJson(u)}
function cardImage(img){img.onerror=()=>{img.src='assets/logo.svg'};img.loading='lazy';img.decoding='async'}
function renderFeatured(el,items){el.innerHTML='';items.slice(0,12).forEach(c=>{const r=(c.rating&&c.rating.toFixed)?c.rating.toFixed(1):(c.rating??'—');const a=document.createElement('a');a.href=c.website;a.target='_blank';a.rel='noopener';a.className='card';a.innerHTML=`<div><img alt="${c.name} logo"><div class='name'>${c.name}</div><div class='meta' style='margin-top:4px;font-size:.85rem;color:#6b7280'>${r}/10</div></div>`;el.appendChild(a);const img=a.querySelector('img');img.src=c.image||'assets/logo.svg';cardImage(img);})}
async function mountIndex(){const idx=await loadIndex();const pills=qs('#pillwrap');const featEl=qs('#feat1');if(!idx){featEl.innerHTML='<p>Data unavailable.</p>';return}pills.innerHTML='';Object.keys(idx).forEach(cat=>{const a=document.createElement('a');a.className='pill';a.textContent=cat;a.href=`category.html?category=${encodeURIComponent(cat)}`;pills.appendChild(a)});const urls=Object.values(idx);const loaded=await Promise.all(urls.slice(0,4).map(loadCategory));const all=loaded.flat().filter(Boolean);all.sort(()=>Math.random()-0.5);renderFeatured(featEl,all);const form=qs('#globalSearch'),input=qs('#searchInput');form.addEventListener('submit',e=>{e.preventDefault();const q=(input.value||'').trim();if(!q)return;location.href=`category.html?category=${encodeURIComponent('Browse All')}&search=${encodeURIComponent(q)}`})}
async function mountCategory(){const p=new URLSearchParams(location.search);const cat=decodeURIComponent(p.get('category')||'Browse All');const pre=decodeURIComponent(p.get('search')||'');const idx=await loadIndex();if(!idx)return;qs('#catTitle').textContent=cat;let data=[];if(cat==='Browse All'){const files=Object.values(idx);const loaded=await Promise.all(files.map(loadCategory));data=loaded.flat().filter(Boolean)}else{const one=await loadCategory(idx[cat]);data=(one||[])}const qInput=qs('#q');if(qInput)qInput.value=pre;function apply(){const term=(qs('#q')?.value||'').toLowerCase().trim();const size=qs('#size')?.value||'';const ver=qs('#ver')?.checked||false;const loc=(qs('#loc')?.value||'').toLowerCase().trim();const view=data.filter(c=>{const t=!term||(c.name+' '+(c.blurb||'')).toLowerCase().includes(term);const s=!size||(c.size||'').toLowerCase()===size.toLowerCase();const v=!ver||!!c.verified;const l=!loc||(c.location||'').toLowerCase().includes(loc);return t&&s&&v&&l});render(1,view)}function render(page,view){const list=qs('#results');list.innerHTML='';const start=(page-1)*PAGE_SIZE;view.slice(start,start+PAGE_SIZE).forEach(c=>{const r=(c.rating&&c.rating.toFixed)?c.rating.toFixed(1):(c.rating??'—');const d=document.createElement('div');d.className='item';d.innerHTML=`<img class='thumb' alt='${c.name} logo'><div style='flex:1'><div style='display:flex;justify-content:space-between;align-items:center;gap:12px;'><h3 style='margin:0'>${c.name}</h3><div class='rating' style='font-weight:700;'>${r}/10</div></div><div class='meta'>${c.category} · ${c.location||'—'} · ${c.size||'—'}</div><p style='margin:.4rem 0 0'>${c.blurb||''}</p><div class='actions'><a class='btn' href='rating.html?id=${encodeURIComponent(c.id)}'>Why this rating?</a><a class='btn primary' href='${c.website}' target='_blank' rel='noopener'>Donate / Official Site</a></div></div>`;list.appendChild(d);const img=d.querySelector('img.thumb');img.src=c.image||'assets/logo.svg';cardImage(img)});qs('#count').textContent=`${view.length}`;const pag=qs('#pag');pag.innerHTML='';const pages=Math.max(1,Math.ceil(view.length/PAGE_SIZE));for(let i=1;i<=pages;i++){const b=document.createElement('button');b.className='btn';b.textContent=i;if(i===page){b.style.background='#1E4D8B';b.style.color='#fff'}b.addEventListener('click',()=>render(i,view));pag.appendChild(b)}}qsa('input,select').forEach(el=>el.addEventListener('input',apply));qs('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();apply()});apply()}
document.addEventListener('DOMContentLoaded',()=>{const page=document.body.dataset.page;if(page==='index')mountIndex();if(page==='category')mountCategory()});
